### ISSUE TITLE
Xamarin.Firebase.Firestore missing prerequisite Xamarin.Google.Guava

### ISSUE THREAD

**Issue by matgallacher** [xamarin/GooglePlayServicesComponents#161]
### Xamarin.Android Version (eg: 6.0):
60.1142.1

### Operating System & Version (eg: Mac OSX 10.11):
Android (any)

### Google Play Services Version (eg: 8.4.0):
Xamarin.Android Bindings for Firebase - Firestore 11.4.2

### Describe your Issue:
Calling .Get on any query throw the exception below

### Steps to Reproduce (with link to sample solution if possible):
var gmsTask = FirebaseFirestore.Instance.Collection("/path/to/collection").Get();

### Include any relevant Exception Stack traces, build logs, adb logs:

11-16 09:25:39.686 E/AndroidRuntime(25554): java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.google.android.gms.internal.zzejs.run(Unknown Source:21)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at android.os.Handler.handleCallback(Handler.java:790)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at android.os.Looper.loop(Looper.java:164)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.lang.reflect.Method.invoke(Native Method)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-16 09:25:39.686 E/AndroidRuntime(25554): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/base/Preconditions;
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbm.<init>(Unknown Source:5)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbm.<init>(Unknown Source:0)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbi.<init>(Unknown Source:1)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbi.<init>(Unknown Source:0)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbm.zza(Unknown Source:3)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.internal.GrpcUtil.<clinit>(Unknown Source:42)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(Unknown Source:20)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.okhttp.zzp.zzty(Unknown Source:0)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.okhttp.OkHttpChannelProvider.zztt(Unknown Source:0)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at io.grpc.zzbc.forTarget(Unknown Source:4)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.google.android.gms.internal.zzeid.<init>(Unknown Source:22)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.google.android.gms.internal.zzeca.zza(Unknown Source:74)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.google.android.gms.internal.zzecc.run(Unknown Source:8)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at com.google.android.gms.internal.zzejp$zza.run(Unknown Source:7)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.lang.Thread.run(Thread.java:764)
11-16 09:25:39.686 E/AndroidRuntime(25554): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.base.Preconditions" on path: DexPathList[[zip file "/data/app/uk.co.gastag.safehome-LXKUCCf3KhiNlf7fjJZxFA==/base.apk"],nativeLibraryDirectories=[/data/app/uk.co.gastag.safehome-LXKUCCf3KhiNlf7fjJZxFA==/lib/x86, /system/fake-libs, /data/app/uk.co.gastag.safehome-LXKUCCf3KhiNlf7fjJZxFA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-16 09:25:39.686 E/AndroidRuntime(25554): 	... 20 more

**Comment by matgallacher** [comment]
I think this is a replication of #130
