### ISSUE TITLE
Cake build script not able execute correctly.

### ISSUE THREAD

**Issue by dzeping96** [xamarin/GooglePlayServicesComponents#173]
### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue:
I try to execute Cake build script for the following sample solution, but it occur error "The target externals' was not found." After that I try to check the provided build.cake script file and there is no task with "externals" inside.

I had saw the original version of this project at https://github.com/xamarin/GooglePlayServicesComponents but this version do not provide Firebase ML Kit Vision API.

### Steps to Reproduce (with link to sample solution if possible):
Sample solution link: https://github.com/xamarin/GooglePlayServicesComponents/tree/15.0.1-binderate
Step 1:
Execute cake build script with command below:-
`powershell .\build.ps1 -Target externals`

Error screenshot:
![image](https://user-images.githubusercontent.com/23049317/50555921-c3124080-0d0d-11e9-966f-6529130ad68b.png)

### Include any relevant Exception Stack traces, build logs, adb logs:
```
System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: The target 'externals' was not found.
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
---> (Inner Exception #0) Cake.Core.CakeException: The target 'externals' was not found.
   at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
```

> VS bug [#760353](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/760353)

**Comment by Redth** [comment]
try: `.\build.ps1 --target=externals`

**Comment by moljac** [comment]
I did not update the doc for building the repo for the new "binderate" project structure and build concept:

The command should be:

Oneliner on Mac:
```
sh ./build.sh --target=binderate && sh ./build.sh --target=libs && sh ./build.sh --target=nuget
``` 
Oneliner in PS on Windows:

```
./build.ps1 --target=binderate && ./build.ps1 --target=libs && ./build.ps1 --target=nuget
```
README.md is updated accordingly.

Closing this one.
