### ISSUE TITLE
Xamarin.Firebase.Messaging No custom notification sound if app is not running, stopped or closed

### ISSUE THREAD

**Issue by tkingston** [xamarin/GooglePlayServicesComponents#186]
### Xamarin.Android Version (eg: 6.0):
Any

### Operating System & Version (eg: Mac OSX 10.11):
Any

### Google Play Services Version (eg: 8.4.0):
Any

### Describe your Issue:
Sending a notification via FCM which uses a custom notification sound is showing the notification on my device but uses the default device notification sound and never plays the specified mp3 notification sound file.

With the following JSON for notification:
`{
	"registration_ids":"tokens",
	"data":{
		"type":"notification",
		"title":"Notification Title",
		"body":"Notification Body",
		"color":"#FF0000",
		"notificationclickaction":"click_action",
		"sound":"notification.mp3",
		"parameters":"parameters"
	},
	"notification":{
		"title":"Notification Title",
		"body":"Notification Body",
		"color":"#FF0000",
		"sound":"notification.mp3"
	}
}`

In the Xamarin Project there is a notification.mp3 inside the Resources/raw folder which does not seem to play.

### Steps to Reproduce (with link to sample solution if possible):
As above.

### Include any relevant Exception Stack traces, build logs, adb logs:
The following error shows in ADB log at the time of push notification:
`03-01 14:22:40.140: W/FirebaseMessaging(16445): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
03-01 14:22:40.140: W/FirebaseMessaging(16445): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source:26)
03-01 14:22:40.140: W/FirebaseMessaging(16445): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:160)`

**Comment by moljac** [comment]
Do you have minimal sample for reproduction? It would help us a lot. Thanks
