### ISSUE TITLE
The "CheckDuplicateJavaLibraries" task failed unexpectedly

### ISSUE THREAD

**Issue by tallkid10** [xamarin/GooglePlayServicesComponents#19]
### Describe your Issue:
I've been trying to build this branch and was following your build instructions.  I first downloaded the zip for version 9.4 and unzipped it.  I then ran the following in powershell:
.\build.ps1 -Target externals -Verbosity diagnostic
I next opened up the GooglePlayServices.sln in VS and tried to build.  Everything built fine with the exception of below that was thrown.  Is this something I need to address or can I ignore?

### Include any relevant Exception Stack traces, build logs, adb logs:
Severity	Code	Description	Project	File	Line	Suppression State
	Error		The "CheckDuplicateJavaLibraries" task failed unexpectedly.
	System.IO.FileNotFoundException: Could not find file '\AppData\Local\Android\android-sdk\extras\android\support\multidex\library\libs\android-support-multidex.jar'.
	File name: '\AppData\Local\Android\android-sdk\extras\android\support\multidex\library\libs\android-support-multidex.jar'
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileInfo.get_Length()
	   at Xamarin.Android.Tasks.MonoAndroidHelper.SizeAndContentFileComparer.GetHashCode(FileInfo obj)
	   at System.Linq.Set`1.InternalGetHashCode(TElement value)
	   at System.Linq.Set`1.Find(TElement value, Boolean add)
	   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at Xamarin.Android.Tasks.MonoAndroidHelper.DistinctFilesByContent(IEnumerable`1 filePaths)
	   at Xamarin.Android.Tasks.CheckDuplicateJavaLibraries.Execute()
	   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	GpsBuildAll

**Comment by Redth** [comment]
Make sure you have "Android Support Library" in the "Extras" section installed in your Android SDK and please try again.

**Comment by tallkid10** [comment]
Thanks @Redth.  I've tried this a couple times after installing "Android Support Repository" and still get the same error.

Here are all the "Extras" I have installed currently.
![image](https://cloud.githubusercontent.com/assets/21262034/18053523/81707fe6-6dc5-11e6-87b6-b0090a668985.png)

**Comment by Redth** [comment]
@tallkid10 you actually need to have "Android Support Library" installed... I'm not sure why it's not showing up in your feed of available items to install...  Investigating that currently as we have the same issue on some systems here...

**Comment by Redth** [comment]
@tallkid10 looks like you have to check the "Obsolete" option in SDK manager to show "Android Support Library (Obsolete)".  This should be installed and your build should get past this error.

**Comment by tallkid10** [comment]
Thanks @Redth !
