### ISSUE TITLE
Visual Studio 2019 Preview's Android Layout Designer raises exception for AndroidX's AppCompatActivity 

### ISSUE THREAD

**Issue by horaciojcfilho** [xamarin/GooglePlayServicesComponents#242]
### Xamarin.Android Version (eg: 6.0):
Visual Studio 2019 16.3 Preview 1
Xamarin.Android 9.5.0.27

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 May 2019 Update

### Google Play Services Version (eg: 8.4.0):
Xamarin.AndroidX.AppCompat 1.0.2-preview01

### Describe your Issue:
As soon as I move from `Support Library's AppCompatActivity` to `AndroidX's AppCompatActivity`, the `Android Layout Designer` raises the following exception:
```
Setting id 1 on newly created ClassLoader

Failed to process message Load
mono.android.DesignerException: java.lang.ClassNotFoundException
	at mono.android.DesignerException.fromThrowable(DesignerException.java:31)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:214)
	at mono.android.DesignerSession.load(DesignerSession.java:276)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:649)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: androidx.collection.ArrayMap
	at mono.android.LibraryClassLoader.loadAndConvertClass(LibraryClassLoader.java:66)
	at mono.android.LibraryClassLoader.findClass(LibraryClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at androidx.appcompat.app.AppCompatViewInflater.<clinit>(AppCompatViewInflater.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.BridgeInflater.createViewFromCustomInflater(BridgeInflater.java:257)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:124)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:310)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:91)
	at com.android.layoutlib.bridge.bars.StatusBar.<init>(StatusBar.java:68)
	at com.android.layoutlib.bridge.impl.Layout.createStatusBar(Layout.java:248)
	at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:159)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:288)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:391)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:271)
	at mono.android.DesignerSession.load(DesignerSession.java:263)
	... 4 more
```

### Steps to Reproduce (with link to sample solution if possible):
- Open the attached sample app [BluetoothLEAndroid.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/3443096/BluetoothLEAndroid.zip)
- Open the `activity_layout.xml` file
- Wait the `Android Layout Designer` finish its work

**Expected:** The `Android Layout Designer` shows the layout without issues.
**Actual:** The `Android Layout Designer` raises an exception while trying to show the layout.

**Comment by horaciojcfilho** [comment]
Please ignore this, I created the issue on the wrong place, it should have been created in https://github.com/xamarin/AndroidSupportComponents instead. Thank you.
