### ISSUE TITLE
Duplicate class definitions when upgrading to 32.940.0-beta3

### ISSUE THREAD

**Issue by thomasvdb** [xamarin/GooglePlayServicesComponents#29]
### Xamarin.Android Version:

Version 6.1.1 (build 15)
Installation UUID: c8d9d174-a2c8-4101-870c-d07ece81c653
Runtime:
    Mono 4.6.1 (mono-4.6.0-branch-c8sr0/ef43c15) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)
    Package version: 406010005
### Operating System & Version:

Max OSX 10.11.6
### Google Play Services Version:

32.940.0-beta3
### Describe your Issue:

I did an upgrade of the Android Support Libraries to v24-rc1 (https://github.com/xamarin/AndroidSupportComponents/issues/11) but when running our app with this update, we receive the following error:

```
[AndroidRuntime] FATAL EXCEPTION: IntentService[GCMRegistrationService]
[AndroidRuntime] java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat
[AndroidRuntime]    at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
[AndroidRuntime]    at com.google.android.gms.iid.zzd.<init>(Unknown Source)
[AndroidRuntime]    at com.google.android.gms.iid.zzd.<init>(Unknown Source)
[AndroidRuntime]    at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
[AndroidRuntime]    at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
[AndroidRuntime]    at com.pushwoosh.GCMRegistrationService.a(Unknown Source)
[AndroidRuntime]    at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
[AndroidRuntime]    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[AndroidRuntime]    at android.os.Handler.dispatchMessage(Handler.java:102)
[AndroidRuntime]    at android.os.Looper.loop(Looper.java:146)
[AndroidRuntime]    at android.os.HandlerThread.run(HandlerThread.java:61)
```

After this error I upgraded the Xamarin.GooglePlayServices.Gcm to 32.940.0-beta3 but I now get the following compile error:

```
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Tool exited with code: 10. Output: Note: there were 332 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-support-multidex.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [bolts-tasks.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [gson.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [com.github.chrisbanes.photoview.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [picasso-2.5.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [play-services-base-8.4.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [play-services-basement-8.4.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [play-services-gcm-8.4.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [play-services-location-8.4.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
Error: Can't write [/private/tmp/mainDexClasses-2681.tmp.jar] (Can't read [/Users/thomasvdb/.local/share/Xamarin/Xamarin.GooglePlayServices.Basement/9.4.0/embedded/classes.jar] (Duplicate zip entry [classes.jar:com/google/android/gms/common/annotation/KeepName.class]))
```

We have the multi-dex option enabled in our build but even with the option disabled I can't compile.
At that point I get the following error:
`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/dynamite/descriptors/com/google/android/gms/flags/ModuleDescriptor;`

When I upgraded to v24 of the support libraries I also needed to update Proguard manually and downloaded version 5.3 (https://sourceforge.net/projects/proguard/files/proguard/), due to this [Xamarin bug](https://bugzilla.xamarin.com/show_bug.cgi?id=44187).

**Comment by Redth** [comment]
Please try the latest stable or latest pre-release versions.  This should be fixed.
