### ISSUE TITLE
TagManager not working (Xamarin.Android)

### ISSUE THREAD

**Issue by TesByRus** [xamarin/GooglePlayServicesComponents#303]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 10.1.4.0 

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX 10.15.1

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Ads.Identifier 71.1600.0
Xamarin.GooglePlayServices.Analytics.Impl 71.1608.0
Xamarin.GooglePlayServices.Basement 71.1620.0
Xamarin.GooglePlayServices.Measurement.Base 71.1630.0
Xamarin.GooglePlayServices.Stats 71.1601.0
Xamarin.GooglePlayServices.TagManager 71.1604.0
Xamarin.GooglePlayServices.TagManager.Api 71.1604.0

### Describe your Issue:
Tag manager not working with Firebase analytics.
I can see firebase events, unlike GTM.

GTM Tag:
![Снимок экрана 2020-02-18 в 09 53 44](https://user-images.githubusercontent.com/3996394/74705121-96ccc280-5234-11ea-8027-361148ad9d9c.png)

Firebase events:
![Снимок экрана 2020-02-18 в 09 51 22](https://user-images.githubusercontent.com/3996394/74705149-aba95600-5234-11ea-90f4-2bba91d97300.png)

Same scenario works well on native app.

Also,  if I try to open GTM preview link, throwing NoSuchMethodError exception

### Steps to Reproduce (with link to sample solution if possible):
Sample project: https://github.com/TesByRus/gtm_xamarin_test
I'm created GTM tag with type of Google Analytics (Firebase). 

### Include any relevant Exception Stack traces, build logs, adb logs:

[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.some_company.some_app, PID: 30344
[AndroidRuntime] java.lang.NoSuchMethodError: No virtual method transactAndReadExceptionReturnVoid(ILandroid/os/Parcel;)V in class Lcom/google/android/gms/internal/measurement/zzq; or its super classes (declaration of 'com.google.android.gms.internal.measurement.zzq' appears in /data/app/com.host.medved_telemed_general-qXxlrIZiYytj-bS41MN-Ng==/base.apk)
[AndroidRuntime] 	at com.google.android.gms.tagmanager.zzcr.previewIntent(Unknown Source:20)
[AndroidRuntime] 	at com.google.android.gms.tagmanager.zzbf.zza(Unknown Source:35)
[AndroidRuntime] 	at com.google.android.gms.tagmanager.TagManagerPreviewActivity.onCreate(Unknown Source:8)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7149)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7140)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
[AndroidRuntime] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
[AndroidRuntime] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6898)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Rews** [comment]
I have exactly the same problem, does anyone know a solution?

**Comment by aian23** [comment]
Did this ever got fixed?

**Comment by wcoder** [comment]
Look at this answer: https://github.com/xamarin/GooglePlayServicesComponents/issues/260#issuecomment-921621269
