### ISSUE TITLE
NoSuchFieldError when building with release configuration on field GOOGLE_SIGN_IN_API

### ISSUE THREAD

**Issue by EdvinM** [xamarin/GooglePlayServicesComponents#323]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android 10.2

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Auth - version: 71.1600.0

### Describe your Issue:
The problem that I'm facing is when I want to build with _release mode configuration_, where Linker is set to **Link SDK assemblies only** I receive the error below, on line where I setup my android login manager.

I am not facing this issue in debug mode (linker on **Don't Link**) 
I tried many steps to avoid it, like adding LinkerPleaseInclude (as seen below) but same results. 
I am using the latest xamarin version.

### Include any relevant Exception Stack traces, build logs, adb logs:
```
at Java.Interop.JniEnvironment+StaticFields.GetStaticFieldID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <77d5f2e313eb463b8bdefaf1a51d5ecd>:0 
  at Java.Interop.JniType.GetStaticField (System.String name, System.String signature) [0x0000c] in <77d5f2e313eb463b8bdefaf1a51d5ecd>:0 
  at Java.Interop.JniPeerMembers+JniStaticFields.GetFieldInfo (System.String encodedMember) [0x00036] in <77d5f2e313eb463b8bdefaf1a51d5ecd>:0 
  at Java.Interop.JniPeerMembers+JniStaticFields.GetObjectValue (System.String encodedMember) [0x00000] in <77d5f2e313eb463b8bdefaf1a51d5ecd>:0 
  at Android.Gms.Auth.Api.Auth.get_GOOGLE_SIGN_IN_API () [0x0000a] in <bd8f8b841b8a49f6a606334f1339e322>:0 
  at ElysiumSpa.Droid.Services.GoogleLoginManager..ctor () [0x00027] in <0a0f93415bd44b14a79111111f603f02>:0 
  --- End of managed Java.Lang.IncompatibleClassChangeError stack trace ---
java.lang.NoSuchFieldError: no "Lcom/google/android/gms/common/api/Api;" field "GOOGLE_SIGN_IN_API" in class "Lcom/google/android/gms/auth/api/Auth;" or its superclasses
	at crc643f46942d9dd1fff9.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at crc643f46942d9dd1fff9.ButtonRenderer_ButtonClickListener.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
  at ElysiumSpa.Droid.Services.GoogleLoginMana04-14 15:41:24.541 I/mono-stdout(16976): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

```
public class LinkerPleaseInclude
    {
        public void Include(GoogleSignInOptions arg)
        {
            arg = new GoogleSignInOptions.Builder().Build();
        }

        public void Include(GoogleApiClient arg)
        {
            arg = new GoogleApiClient.Builder(CrossCurrentActivity.Current.AppContext).Build();
        }

        public void Include(Api arg)
        {
            arg = Auth.GOOGLE_SIGN_IN_API;
        }
    }
```

**Comment by moljac** [comment]
@EdvinM 

Can you try adding proguard rule (something like):

```
-keep class com.google.android.gms.common.api.Api { *; } 
```
??

**Comment by moljac** [comment]
The C# MCW is generated:

```
		// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.gms.auth.api']/class[@name='Auth']/field[@name='GOOGLE_SIGN_IN_API']"
		[Register ("GOOGLE_SIGN_IN_API")]
		public static global::Android.Gms.Common.Apis.Api GOOGLE_SIGN_IN_API {
			get {
				const string __id = "GOOGLE_SIGN_IN_API.Lcom/google/android/gms/common/api/Api;";

				var __v = _members.StaticFields.GetObjectValue (__id);
				return global::Java.Lang.Object.GetObject<global::Android.Gms.Common.Apis.Api> (__v.Handle, JniHandleOwnership.TransferLocalRef);
			}
		}
```

**Comment by EdvinM** [comment]
> @EdvinM
> 
> Can you try adding proguard rule (something like):
> 
> ```
> -keep class com.google.android.gms.common.api.Api { *; } 
> ```
> 
> ??

@moljac I tried to create a proguard config file and added this line, but same result. Btw, I am building the app using Dex Compiler **d8** and **r8** code shrinker.

**Comment by moljac** [comment]
@EdvinM 

R8 is replacement for proguard, so no worries for using it.

Maybe try:

```
-keep class com.google.android.gms.common.api.Api
```

See some similar discussion:

https://github.com/xamarin/AndroidX/issues/74#issuecomment-613526927

**Comment by moljac** [comment]
@EdvinM 

Maybe Xamarin mono linker is the one that strips that field.

https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

So I guess your config might look like (of top of my head):

```
<linker>
    <assembly 
        fullname="Xamarin.GooglePlayServices.Auth"
        >
        <type 
            fullname="Android.Gms.Common.Apis.Api"
            >
            <field 
                name="GOOGLE_SIGN_IN_API" 
                />
        </type>
    </assembly>
</linker>
```
or maybe:
```
<linker>
    <assembly 
        fullname="Xamarin.GooglePlayServices.Auth"
        >
        <type 
            fullname="Android.Gms.Common.Apis.Api"
            preserve="fields"
            >
        </type>
    </assembly>
</linker>
```    

Can you provide feedback if that helped?

**Comment by EdvinM** [comment]
@moljac I tried the configs for the linker you posted, but I get the same results. 

I have managed to fix this issue though, using as you suggested previously proguard, but with different configuration. Using this config:
```
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
```
works.

**Comment by moljac** [comment]
@EdvinM 
Excellent. Thanks for the feedback. Appreciated.

Closing this issue.
