### ISSUE TITLE
Xamarin.Firebase.Crashlytics Java.Lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/GooglePlayServicesComponents#393]
### Xamarin.Android Version (eg: 6.0):

11.1.0.17 (16.8 Preview)

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10

### Google Play Services Version

*   [x] GPS-FB with AndroidX dependencies (versions `1xx.yyyy.zz`)

### Describe your Issue

App crashes with:
```
Java.Lang.NoSuchMethodError: 'No static method checkBuilderRequirement(Ljava/lang/Object;Ljava/lang/Class;)V in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.jonathanpeppers.firebasetest-1/base.apk)'
```

The problem is solved by adding `<PackageReference Include="Xamarin.Google.Dagger" Version="2.25.2.1" />`, so I think we just need to add a dependency to the `.nuspec`?

### Relevant information

Add relevant project settings from `*.csproj` file:

Packages used:

```
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.2.0.4" />
    <PackageReference Include="Xamarin.Firebase.Crashlytics" Version="117.0.0" />
```

### Minimal Repro Code Sample

https://github.com/jonathanpeppers/xamarin-crashes

### Include any relevant Exception Stack traces, build logs, adb logs:

Extended `adb logcat` output (if helpful):
```
10-26 17:06:59.130 17650 17650 I FirebaseCrashlytics: Initializing Crashlytics 17.0.0
10-26 17:06:59.138 17650 17650 I art     : Rejecting re-init on previously-failed class java.lang.Class<dagger.internal.Factory>: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider;
10-26 17:06:59.138 17650 17650 I art     :   at com.google.android.datatransport.runtime.TransportRuntimeComponent$Builder com.google.android.datatransport.runtime.DaggerTransportRuntimeComponent.builder() (com.google.android.datatransport:transport-runtime@@2.2.1:74)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.android.datatransport.runtime.TransportRuntime.initialize(android.content.Context) (com.google.android.datatransport:transport-runtime@@2.2.1:76)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender.create(android.content.Context) (com.google.firebase:firebase-crashlytics@@17.0.0:52)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.create(android.content.Context, com.google.firebase.crashlytics.internal.common.IdManager, com.google.firebase.crashlytics.internal.persistence.FileStore, com.google.firebase.crashlytics.internal.common.AppData, com.google.firebase.crashlytics.internal.log.LogFileManager, com.google.firebase.crashlytics.internal.common.UserMetadata, com.google.firebase.crashlytics.internal.stacktrace.StackTraceTrimmingStrategy, com.google.firebase.crashlytics.internal.settings.SettingsDataProvider) (com.google.firebase:firebase-crashlytics@@17.0.0:65)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.crashlytics.internal.common.CrashlyticsController.<init>(android.content.Context, com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker, com.google.firebase.crashlytics.internal.network.HttpRequestFactory, com.google.firebase.crashlytics.internal.common.IdManager, com.google.firebase.crashlytics.internal.common.DataCollectionArbiter, com.google.firebase.crashlytics.internal.persistence.FileStore, com.google.firebase.crashlytics.internal.common.CrashlyticsFileMarker, com.google.firebase.crashlytics.internal.common.AppData, com.google.firebase.crashlytics.internal.report.ReportManager, com.google.firebase.crashlytics.internal.report.ReportUploader$Provider, com.google.firebase.crashlytics.internal.CrashlyticsNativeComponent, com.google.firebase.crashlytics.internal.unity.UnityVersionProvider, com.google.firebase.crashlytics.internal.analytics.AnalyticsReceiver, com.google.firebase.analytics.connector.AnalyticsConnector, com.google.firebase.crashlytics.interna
10-26 17:06:59.138 17650 17650 I art     :   at boolean com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(com.google.firebase.crashlytics.internal.settings.SettingsDataProvider) (com.google.firebase:firebase-crashlytics@@17.0.0:165)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.FirebaseCrashlytics.init(com.google.firebase.FirebaseApp, com.google.firebase.iid.internal.FirebaseInstanceIdInternal, com.google.firebase.crashlytics.internal.CrashlyticsNativeComponent, com.google.firebase.analytics.connector.AnalyticsConnector) (com.google.firebase:firebase-crashlytics@@17.0.0:78)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:55)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.CrashlyticsRegistrar.access$lambda$0(com.google.firebase.crashlytics.CrashlyticsRegistrar, com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.crashlytics.CrashlyticsRegistrar$$Lambda$1.create(com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase.components.ComponentRuntime, com.google.firebase.components.Component) (com.google.firebase:firebase-components@@16.0.0:69)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.ComponentRuntime$$Lambda$1.get() (com.google.firebase:firebase-components@@16.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.Lazy.get() (com.google.firebase:firebase-components@@16.0.0:53)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.components.ComponentRuntime.initializeEagerComponents(boolean) (com.google.firebase:firebase-components@@16.0.0:158)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.FirebaseApp.initializeAllApis() (com.google.firebase:firebase-common@@19.3.0:563)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (com.google.firebase:firebase-common@@19.3.0:304)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (com.google.firebase:firebase-common@@19.3.0:268)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (com.google.firebase:firebase-common@@19.3.0:253)
10-26 17:06:59.138 17650 17650 I art     :   at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (com.google.firebase:firebase-common@@19.3.0:51)
10-26 17:06:59.138 17650 17650 I art     :   at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1751)
10-26 17:06:59.138 17650 17650 I art     :   at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1726)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (com.google.firebase:firebase-common@@19.3.0:45)
10-26 17:06:59.138 17650 17650 I art     :   at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6008)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5590)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5529)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1576)
10-26 17:06:59.138 17650 17650 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-26 17:06:59.138 17650 17650 I art     :   at void android.os.Looper.loop() (Looper.java:241)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6274)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-26 17:06:59.138 17650 17650 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
10-26 17:06:59.138 17650 17650 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
10-26 17:06:59.138 17650 17650 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/com.jonathanpeppers.firebasetest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jonathanpeppers.firebasetest-1/lib/arm64, /data/app/com.jonathanpeppers.firebasetest-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.android.datatransport.runtime.TransportRuntimeComponent$Builder com.google.android.datatransport.runtime.DaggerTransportRuntimeComponent.builder() (com.google.android.datatransport:transport-runtime@@2.2.1:74)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.android.datatransport.runtime.TransportRuntime.initialize(android.content.Context) (com.google.android.datatransport:transport-runtime@@2.2.1:76)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender com.google.firebase.crashlytics.internal.send.DataTransportCrashlyticsReportSender.create(android.content.Context) (com.google.firebase:firebase-crashlytics@@17.0.0:52)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator.create(android.content.Context, com.google.firebase.crashlytics.internal.common.IdManager, com.google.firebase.crashlytics.internal.persistence.FileStore, com.google.firebase.crashlytics.internal.common.AppData, com.google.firebase.crashlytics.internal.log.LogFileManager, com.google.firebase.crashlytics.internal.common.UserMetadata, com.google.firebase.crashlytics.internal.stacktrace.StackTraceTrimmingStrategy, com.google.firebase.crashlytics.internal.settings.SettingsDataProvider) (com.google.firebase:firebase-crashlytics@@17.0.0:65)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.crashlytics.internal.common.CrashlyticsController.<init>(android.content.Context, com.google.firebase.crashlytics.internal.common.CrashlyticsBackgroundWorker, com.google.firebase.crashlytics.internal.network.HttpRequestFactory, com.google.firebase.crashlytics.internal.common.IdManager, com.google.firebase.crashlytics.internal.common.DataCollectionArbiter, com.google.firebase.crashlytics.internal.persistence.FileStore, com.google.firebase.crashlytics.internal.common.CrashlyticsFileMarker, com.google.firebase.crashlytics.internal.common.AppData, com.google.firebase.crashlytics.internal.report.ReportManager, com.google.firebase.crashlytics.internal.report.ReportUploader$Provider, com.google.firebase.crashlytics.internal.CrashlyticsNativeComponent, com.google.firebase.crashlytics.internal.unity.UnityVersionProvider, com.google.firebase.crashlytics.internal.analytics.AnalyticsReceiver, com.google.firebase.analytics.connector.AnalyticsConnector, com.google.firebase.crashlytics.interna
10-26 17:06:59.138 17650 17650 I art     :   at boolean com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(com.google.firebase.crashlytics.internal.settings.SettingsDataProvider) (com.google.firebase:firebase-crashlytics@@17.0.0:165)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.FirebaseCrashlytics.init(com.google.firebase.FirebaseApp, com.google.firebase.iid.internal.FirebaseInstanceIdInternal, com.google.firebase.crashlytics.internal.CrashlyticsNativeComponent, com.google.firebase.analytics.connector.AnalyticsConnector) (com.google.firebase:firebase-crashlytics@@17.0.0:78)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:55)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.crashlytics.FirebaseCrashlytics com.google.firebase.crashlytics.CrashlyticsRegistrar.access$lambda$0(com.google.firebase.crashlytics.CrashlyticsRegistrar, com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.crashlytics.CrashlyticsRegistrar$$Lambda$1.create(com.google.firebase.components.ComponentContainer) (com.google.firebase:firebase-crashlytics@@17.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase.components.ComponentRuntime, com.google.firebase.components.Component) (com.google.firebase:firebase-components@@16.0.0:69)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.ComponentRuntime$$Lambda$1.get() (com.google.firebase:firebase-components@@16.0.0:-1)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object com.google.firebase.components.Lazy.get() (com.google.firebase:firebase-components@@16.0.0:53)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.components.ComponentRuntime.initializeEagerComponents(boolean) (com.google.firebase:firebase-components@@16.0.0:158)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.FirebaseApp.initializeAllApis() (com.google.firebase:firebase-common@@19.3.0:563)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String) (com.google.firebase:firebase-common@@19.3.0:304)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions) (com.google.firebase:firebase-common@@19.3.0:268)
10-26 17:06:59.138 17650 17650 I art     :   at com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context) (com.google.firebase:firebase-common@@19.3.0:253)
10-26 17:06:59.138 17650 17650 I art     :   at boolean com.google.firebase.provider.FirebaseInitProvider.onCreate() (com.google.firebase:firebase-common@@19.3.0:51)
10-26 17:06:59.138 17650 17650 I art     :   at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo, boolean) (ContentProvider.java:1751)
10-26 17:06:59.138 17650 17650 I art     :   at void android.content.ContentProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (ContentProvider.java:1726)
10-26 17:06:59.138 17650 17650 I art     :   at void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android.content.pm.ProviderInfo) (com.google.firebase:firebase-common@@19.3.0:45)
10-26 17:06:59.138 17650 17650 I art     :   at android.app.IActivityManager$ContentProviderHolder android.app.ActivityThread.installProvider(android.content.Context, android.app.IActivityManager$ContentProviderHolder, android.content.pm.ProviderInfo, boolean, boolean, boolean) (ActivityThread.java:6008)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.installContentProviders(android.content.Context, java.util.List) (ActivityThread.java:5590)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5529)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1576)
10-26 17:06:59.138 17650 17650 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
10-26 17:06:59.138 17650 17650 I art     :   at void android.os.Looper.loop() (Looper.java:241)
10-26 17:06:59.138 17650 17650 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6274)
10-26 17:06:59.138 17650 17650 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
10-26 17:06:59.138 17650 17650 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:886)
10-26 17:06:59.138 17650 17650 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:776)
```

**Comment by moljac** [comment]
fixed in: 

https://github.com/xamarin/GooglePlayServicesComponents/commit/337594b0947e01c864994d7e55fd82afbfcf3270

GPS-FB June updates (202006) contain this fix, but not all packages will be pushed today (20201027). The patch will be bumped in following days.

**Comment by Qythyx** [comment]
I'm not 100% sure it is related, but I'm having this same problem. I then added the two PackageReference lines as suggested and now I get this error when my app is starting:

```
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: No static method checkBuilderRequirement(Ljava/lang/Object;Ljava/lang/Class;)V in class Ldagger/internal/Preconditions; or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app/com.qythyx.beerplease-fgrQwbxK73Szb1U_wo29IA==/base.apk)
	at com.google.android.datatransport.runtime.DaggerTransportRuntimeComponent$Builder.build(com.google.android.datatransport:transport-runtime@@2.2.1:112)
	at com.google.android.datatransport.runtime.TransportRuntime.initialize(com.google.android.datatransport:transport-runtime@@2.2.1:78)
	at com.google.firebase.datatransport.TransportRegistrar.lambda$getComponents$0(com.google.firebase:firebase-datatransport@@17.0.5:37)
	at com.google.firebase.datatransport.TransportRegistrar$$Lambda$1.create(Unknown Source:0)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
	at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
	at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
	at com.google.firebase.messaging.zzn.create(com.google.firebase:firebase-messaging@@20.1.7:8)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Qythyx** [comment]
I found [this discussion](https://github.com/xamarin/GooglePlayServicesComponents/issues/385), which links to https://github.com/a-imai/XamarinCrashlyticsUpgradeSample, which describes a complete fix for my `NoSuchMethodError` problem. I just followed the directions there and it worked for me.

**Comment by jonathanpeppers** [comment]
@Qythyx using a newer Xamarin.Google.Dagger NuGet package probably fixed the missing method in `Ldagger/internal/Preconditions`? That would be the only thing that would fix this -- a different `.jar` or `.aar` file.

One note about their their instructions, I found `com.crashlytics.android.build_id` is deprecated:

* https://github.com/firebase/firebase-android-sdk/blob/c78e85203a16458602ac12e2d0a4b315d913749c/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L88-L90
* https://github.com/firebase/firebase-android-sdk/blob/c78e85203a16458602ac12e2d0a4b315d913749c/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L805-L821

I think you should use `com.google.firebase.crashlytics.mapping_file_id` instead, as it will be less likely to break in the future. I think the Crashlytics error message is incorrect to suggest using `build_id`.

Here is my working sample, if it helps anyone:

https://github.com/jonathanpeppers/xamarin-crashes

**Comment by moljac** [comment]
Closing this one.
