### ISSUE TITLE
RecyclerView linker error with Xamarin.Firebase.Messaging v121.1.0

### ISSUE THREAD

**Issue by freever** [xamarin/GooglePlayServicesComponents#472]
### Operating System & Version (eg: Mac OSX 10.11):
Windows and Mac

### Google Play Services Version

 Xamarin.Firebase.Messaging v121.1.0

### Describe your Issue
When I updated my Xamarin.Forms Android (v5.0.0.2012) project to use the latest version of  Xamarin.Firebase.Messaging (v121.1.0) from nuget, building in release mode (linker is set to "Sdk Assemblies only) started failing with the following error:

```
Mono.Linker.MarkException: Error processing method: 'System.Void AndroidX.RecyclerView.Widget.RecyclerView/LayoutManager::n_OnInitializeAccessibilityNodeInfo_Landroidx_recyclerview_widget_RecyclerView_Recycler_Landroidx_recyclerview_widget_RecyclerView_State_Landroidx_core_view_accessibility_AccessibilityNodeInfoCompat_(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)' in assembly: 'Xamarin.AndroidX.RecyclerView.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Core.View.Accessibiity.AccessibilityNodeInfoCompat
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	MineGame.App.Staging.Android		
```	

As soon as I revert to v121.0.1 the problem disappears.

**Comment by jpobst** [comment]
There is an explanation and fix available here: https://github.com/xamarin/AndroidX/issues/283#issuecomment-788103573.

Hope this helps!

**Comment by freever** [comment]
@jpobst Thanks, installing Xamarin.AndroidX.RecyclerView solved the problem!
