### ISSUE TITLE
[BUG] Crash at runtime Xamarin.Firebase.InAppMessaging.Display 120.1.0.2

### ISSUE THREAD

**Issue by AlejandroLemusR** [xamarin/GooglePlayServicesComponents#551]
### Xamarin.Android Version (eg: 6.0):

Version: 11.4.0.5 

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10 Enterprise
Version	21H1

### Google Play Services Version

Xamarin.Firebase.InAppMessaging.Display 120.1.0.2

### Describe your Issue

A runtime crash occurs InAppMessaging.Display. 
This occurs in debug mode.
I have already tried to fix it by adding Guava 27.1.0

### Relevant information

Packages used:

```
<PackageReference Include="Xamarin.Android.Glide">
  <Version>4.12.0</Version>
</PackageReference>
<PackageReference Include="Xamarin.Firebase.InAppMessaging.Display">
  <Version>120.1.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.Firebase.Installations">
  <Version>117.0.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2244" />
<PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
<PackageReference Include="Xamarin.GooglePlayServices.Base">
  <Version>117.6.0.2</Version>
</PackageReference>
<PackageReference Include="Xamarin.GooglePlayServices.TagManager">
  <Version>117.0.1.2</Version>
</PackageReference>
```

Build settings (tools)

```
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidUseAapt2>true</AndroidUseAapt2>
```

Build settings (tools)
Debug mode.

### Minimal Repro Code Sample
[AppTest.zip](https://github.com/xamarin/GooglePlayServicesComponents/files/7682503/AppTest.zip)

### Steps to Reproduce (with link to sample solution if possible):

1. Add you google play services.json
2. Add Package name
3. Run and it will crash just after startup.

### Include any relevant Exception Stack traces, build logs, adb logs:

```
[ProviderInstaller] Installed default security provider GmsCore_OpenSSL
[System.err] io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/base/Preconditions;
[System.err] 	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
[System.err] 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
[System.err] 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
[System.err] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[System.err] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
[System.err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[System.err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[System.err] 	at java.lang.Thread.run(Thread.java:923)
[System.err] Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/base/Preconditions;
[System.err] 	at io.grpc.Metadata$Key.<init>(Metadata.java:749)
[System.err] 	at io.grpc.Metadata$Key.<init>(Metadata.java:668)
[System.err] 	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
[System.err] 	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
[System.err] 	at io.grpc.Metadata$Key.of(Metadata.java:705)
[System.err] 	at io.grpc.Metadata$Key.of(Metadata.java:701)
[System.err] 	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:80)
[System.err] 	at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:90)
[System.err] 	at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(OkHttpChannelBuilder.java:115)
[System.err] 	at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:46)
[System.err] 	at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:26)
[System.err] 	at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule.providesGrpcChannel(GrpcChannelModule.java:41)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.providesGrpcChannel(GrpcChannelModule_ProvidesGrpcChannelFactory.java:39)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.get(GrpcChannelModule_ProvidesGrpcChannelFactory.java:30)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.get(GrpcChannelModule_ProvidesGrpcChannelFactory.java:9)
[System.err] 	at com.google.firebase.inappmessaging.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.components.DaggerUniversalComponent.gRPCChannel(DaggerUniversalComponent.java:180)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.components.DaggerAppComponent$com_google_firebase_inappmessaging_internal_injection_components_UniversalComponent_gRPCChannel.get(DaggerAppComponent.java:309)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.components.DaggerAppComponent$com_google_firebase_inappmessaging_internal_injection_components_UniversalComponent_gRPCChannel.get(DaggerAppComponent.java:299)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.get(GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.java:35)
[System.err] 	at com.google.firebase.inappmessaging.internal.injection.modules.GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.get(GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.java:11)
[System.err] 	at com.google.firebase.inappmessaging.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[System.err] 	at com.google.firebase.inappmessaging.internal.GrpcClient_Factory.get(GrpcClient_Factory.java:26)
[System.err] 	at com.google.firebase.inappmessaging.internal.GrpcClient_Factory.get(GrpcClient_Factory.java:8)
[System.err] 	at com.google.firebase.inappmessaging.dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
[System.err] 	at com.google.firebase.inappmessaging.internal.ApiClient.getFiams(ApiClient.java:72)
[System.err] 	at com.google.firebase.inappmessaging.internal.InAppMessageStreamManager.lambda$createFirebaseInAppMessageStream$16$InAppMessageStreamManager(InAppMessageStreamManager.java:261)
[System.err] 	at com.google.firebase.inappmessaging.internal.-$$Lambda$InAppMessageStreamManager$VxyUxgR76CW5pjlBPvp43BItTTQ.apply(Unknown Source:6)
[System.err] 	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82)
[System.err] 	at io.reactivex.internal.operators.maybe.MaybeFilter$FilterMaybeObserver.onSuccess(MaybeFilter.java:89)
[System.err] 	at io.reactivex.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:103)
[System.err] 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
[System.err] 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
[System.err] 	... 6 more
[System.err] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.base.Preconditions" on path: DexPathList[[zip file "/data/app/~~DO4UjvHltCdFKCCSOiZ4Zw==/app.nmp.movil-x1h6Tg5m0GyI_DY5qCwFxA==/base.apk"],nativeLibraryDirectories=[/data/app/~~DO4UjvHltCdFKCCSOiZ4Zw==/app.nmp.movil-x1h6Tg5m0GyI_DY5qCwFxA==/lib/arm64, /data/app/~~DO4UjvHltCdFKCCSOiZ4Zw==/app.nmp.movil-x1h6Tg5m0GyI_DY5qCwFxA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
[System.err] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
[System.err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[System.err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[System.err] 	... 40 more
[app.nmp.movil] Thread 0x78ec889cc0 may have been prematurely finalized
[app.nmp.movil] * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/utils/mono-threads.c:650, condition `info' not met, function:mono_thread_info_current, 
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3782 (RxCachedThreadS), pid 3713 (app.nmp.movil)
```

**Comment by AlejandroLemusR** [comment]
Hello everyone, I found the solution for this problem, if anyone has this problem they should consider installing the following **nugget settings**:
```
 <PackageReference Include="Xamarin.Google.Guava" ExcludeAssets="all">
   <Version>27.1.0.1</Version>
 </PackageReference>
 <PackageReference Include="Xamarin.Google.Guava.FailureAccess">
   <Version>1.0.1</Version>
 </PackageReference>
 <PackageReference Include="Xamarin.Google.Guava.ListenableFuture" ExcludeAssets="build;buildTransitive">
   <Version>1.0.0.2</Version>
   <IncludeAssets>runtime; compile; native; contentfiles; analyzers</IncludeAssets>
 </PackageReference>
 <PackageReference Include="Xamarin.Android.Glide">
   <Version>4.12.0.2</Version>
 </PackageReference>
 <PackageReference Include="Xamarin.Firebase.Installations">
   <Version>117.0.0.3</Version>
 </PackageReference>
```
