### ISSUE TITLE
Visual Studio Android GooglePlayServices Linking Error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/GooglePlayServicesComponents#574]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Android-GooglePlayServices/1559747)._

---
I'm trying to compile my Android project that uses the Plugin.GoogleClient package. I have the Xamarin.GooglePlayServices.Auth (https://www.nuget.org/packages/Xamarin.GooglePlayServices.Auth/119.2.0.1?_src=template) package installed, however the linker cannot find the GetToken() method even though it is included within that package. Here is the error that I get:

error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.GoogleClient.GoogleClientManager/<>c__DisplayClass48_0::<OnSignInSuccessful>b__1()' in assembly: 'Plugin.GoogleClient.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String Android.Gms.Auth.GoogleAuthUtil::GetToken(Android.Content.Context,Android.Accounts.Account,System.String)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
error XALNK7000:    --- End of inner exception stack trace ---
error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process()
error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
error XALNK7000:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
error XALNK7000:    at Mono.Linker.Pipeline.Process(LinkContext context)
error XALNK7000:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
error XALNK7000:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17

---
#### Feedback Bot on 10/20/2021, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jonathan Pobst [MSFT] on 10/25/2021, 08:37 AM: 

<p>This type looks like it is actually in <code>Xamarin.GooglePlayServices.Auth.Base</code>, and was removed between version <code>117.0</code> and <code>117.1</code>:</p>
<p><a target='_blank' href="https://www.fuget.org/packages/Xamarin.GooglePlayServices.Auth.Base/117.0.0/lib/monoandroid90/Xamarin.GooglePlayServices.Auth.Base.dll/Android.Gms.Auth/GoogleAuthUtil">https://www.fuget.org/packages/Xamarin.GooglePlayServices.Auth.Base/117.0.0/lib/monoandroid90/Xamarin.GooglePlayServices.Auth.Base.dll/Android.Gms.Auth/GoogleAuthUtil</a></p>
<p>I have filed an issue to investigate it to be fixed:</p>
<p><a target='_blank' href="https://github.com/xamarin/GooglePlayServicesComponents/issues/532">https://github.com/xamarin/GooglePlayServicesComponents/issues/532</a></p>
<p>For now, the workaround would be to use the <code>117.0</code> version of the <code>Xamarin.GooglePlayServices.Auth.Base</code> NuGet package.</p>

#### Alexander Perelberg on 11/30/2021, 08:52 AM: 

<p>That workaround does not work.<br>
The only workaround I found was to completely remove Plugin.GoogleClient from the entire Android project.<br>
Please let me know if this issue is going to be fixed in the near future.</p>

#### Feedback Bot on 2/9/2022, 11:27 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by moljac** [comment]
@vsfeedback Thanks for the feedback.

Repro sample maybe? Content of the project files? That would help. Thanks

**Comment by ooikengsiang** [comment]
> @vsfeedback Thanks for the feedback.
> 
> Repro sample maybe? Content of the project files? That would help. Thanks

This issue is the same as https://github.com/xamarin/GooglePlayServicesComponents/issues/532 which is not fixed yet even though the issue is closed
GoogleAuthUtil still missing in the latest Xamarin.GooglePlayServices.Auth.Base
