### ISSUE TITLE
Xamarin.GooglePlayServices.Maps crashes on Android 6/7/8

### ISSUE THREAD

**Issue by tipa** [xamarin/GooglePlayServicesComponents#637]
The latest version 118.0.2.1 of `Xamarin.GooglePlayServices.Maps` crashes on lower Android versions (confirmed on 6, 7 & 8) during runtime when initializing the MapView (either using MapView  directly or (Support)MapFragment). There are no issues with 118.0.2.0

Exception:
`Java.Lang.LinkageError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.google.android.gms.dynamic.ObjectWrapper' appears in /data/app/my.app-gjPBFDBm6B9Szn0XDe01ew==/base.apk)
`

Stacktrace:
```
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
MapView.OnCreate (Android.OS.Bundle savedInstanceState)
DetailsActivity.OnCreate (Android.OS.Bundle savedInstanceState)
Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0)
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.google.android.gms.dynamic.ObjectWrapper' appears in /data/app/my.app-gjPBFDBm6B9Szn0XDe01ew==/base.apk)
com.google.android.gms.dynamic.ObjectWrapper.unwrap(com.google.android.gms:play-services-basement@@18.0.2:4)
com.google.android.gms.maps.zzag.onCreate(com.google.android.gms:play-services-maps@@18.0.0:5)
com.google.android.gms.dynamic.zac.zab(com.google.android.gms:play-services-base@@18.0.1:1)
com.google.android.gms.dynamic.zaa.onDelegateCreated(com.google.android.gms:play-services-base@@18.0.1:3)
com.google.android.gms.maps.zzah.zzb(com.google.android.gms:play-services-maps@@18.0.0:5)
com.google.android.gms.maps.zzah.createDelegate(com.google.android.gms:play-services-maps@@18.0.0:1)
com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.0.1:6)
com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.0.1:1)
com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.0.0:4)
crc64f0370c7dabd1a455.DetailsActivity.n_onCreate(Native Method)
crc64f0370c7dabd1a455.DetailsActivity.onCreate DetailsActivity.java:46
android.app.Activity.performCreate Activity.java:7383
android.app.Instrumentation.callActivityOnCreate Instrumentation.java:1218
android.app.ActivityThread.performLaunchActivity ActivityThread.java:3256
android.app.ActivityThread.handleLaunchActivity ActivityThread.java:3411
android.app.ActivityThread.-wrap12(Unknown Source:0)
android.app.ActivityThread$H.handleMessage ActivityThread.java:1994
android.os.Handler.dispatchMessage Handler.java:108
android.os.Looper.loop Looper.java:166
android.app.ActivityThread.main ActivityThread.java:7529
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:245
com.android.internal.os.ZygoteInit.main ZygoteInit.java:921
```

Demo project:
[App1.zip](https://github.com/xamarin/XamarinComponents/files/8883673/App1.zip)

Additional info:
I think the other packages like `Xamarin.GooglePlayServices.Ads.Lite` are suffering from the same problem

**Comment by jvreeker** [comment]
I have problems with admob see error. Any solution about this issue

	at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@20.6.0:1)
     FATAL EXCEPTION: Thread-10
Process: nl.vappz.Weather, PID: 29815
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.google.android.gms.dynamic.ObjectWrapper' appears in /data/app/nl.vappz.Weather-wzlI5h4BcVdCMg8hgpedtg==/base.apk)
	at com.google.android.gms.dynamic.ObjectWrapper.unwrap(com.google.android.gms:play-services-basement@@18.0.2:4)
	at com.google.android.gms.internal.ads.zzbji.zzl(com.google.android.gms:play-services-ads-lite@@20.6.0:20)
	at com.google.android.gms.ads.BaseAdView.loadAd(com.google.android.gms:play-services-ads-lite@@20.6.0:1)
	at crc64a613c5ab8fad43f6.SearchFragment.n_onCreateView(Native Method)
	at crc64a613c5ab8fad43f6.SearchFragment.onCreateView(SearchFragment.java:57)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:22116)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6654)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:731)
	at android.view.View.measure(View.java:22116)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2497)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1563)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1827)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7150)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:7)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6703)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Comment by o0k4m1** [comment]
I have exact same issue and we cannot update some libraries that depend on this. It would be great to have a fix soon!

**Comment by csm101** [comment]
Same problem here...

**Comment by lukegore** [comment]
I had the same problem. In my case just downgrading `Xamarin.GooglePlayServices.Maps` to version `118.0.2` didn't solve it, since it seems that `Xamarin.GooglePlayServices.Basement 118.0.2.1` causes this issue. I had to downgrade other packages like `Xamarin.Firebase.*`, too.

Downgrading all NuGet packages that depend on this package with version `18.0.0` or lower solved the problem for now.

**Comment by tipa** [comment]
From what I can tell, the problem has been resolved with the last Nuget version - thanks!

**Comment by jonathanantoine** [comment]
Same problem for me, it happens only on Samsung devices (Galaxy S9 for instance) as far as I know.
