### ISSUE TITLE
Getting Exception while tracking Network calls

### ISSUE THREAD

**Issue by NiladriPadhy** [xamarin/GooglePlayServicesComponents#644]
### Xamarin.Android Version (eg: 6.0):
Version: 8.8.0.3 (Visual Studio Professional)

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS Montere 12.3 (21E230)

### Xamrin.Firebase.Perf Version
120.0.2.3

### Describe your Issue
Getting Exception while manually tracing network calls.
Reffered Link: https://www.oliverbrown.me.uk/2021/09/07/solved-firebase-performance-monitoring-in-xamarin-android/
Manually adding netowrk tracking because for below open issue
https://github.com/xamarin/GooglePlayServicesComponents/issues/172

### Relevant information
There is an updated version for Xamarin.Firebase.Perf, which is 120.0.2.6. But the updated version is not installing, which requires .net 6. Currently I am using Visual studio 2019. I can't upgrade to  6.0.

Sample code:

```csharp
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Firebase.Perf.Metrics;
using Jacobs.Helpers;

namespace FirebasePerformanceMonitorSample.Droid
{
    public class AndroidHttpClient 
    {
        public AndroidHttpClient()
        {
        }

        public async Task<HttpResponseMessage> GetHttpResponseMessage(string url)
        {
            var metric = StartTracking(null,url,"GET");

            var client = new HttpClient()
            {
                BaseAddress = new Uri(Configurations.BaseUrl)
            };
            var token = AppConstants.APIAccessToken;

            client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
            client.DefaultRequestHeaders.Add("Accept", "application/json");
            var response = await client.GetAsync(url);
            StopTracking(metric, response);
            return response;
        }
        private HttpMetric? StartTracking(HttpRequestMessage request,string uri, string method)
        {
            try
            {
                var url = new Java.Net.URL(Configurations.BaseUrl+uri);
                **var metric = Firebase.Perf.FirebasePerformance.Instance.NewHttpMetric(url, method);**
                metric.Start();
                if (request?.Content?.Headers?.ContentLength is long length)
                {
                    metric.SetRequestPayloadSize(length);
                }

                return metric;
            }
            catch (Exception ex)
            {
                Debug.Fail($"URL performance tracking failed: {request.RequestUri.AbsoluteUri} - {ex.Message}");
                return null;
            }
        }

        private void StopTracking(HttpMetric? metric, HttpResponseMessage response)
        {
            if (metric is null)
            {
                return;
            }
            try
            {
                metric.SetHttpResponseCode((int)response.StatusCode);
                if (response.Content?.Headers?.ContentLength is long length)
                {
                    metric.SetResponsePayloadSize(length);
                }
                if (response.Content?.Headers?.ContentType?.MediaType is string mediaType)
                {
                    metric.SetResponseContentType(mediaType);
                }
            }
            catch (Exception ex)
            {
                Debug.Fail($"URL performance tracking failed: {response.RequestMessage.RequestUri.AbsoluteUri} - {ex.Message}");
            }
            finally
            {
                metric.Stop();
            }
        }
    }
}
```

Getting exception is this   **`var metric = Firebase.Perf.FirebasePerformance.Instance.NewHttpMetric(url, method);`** like of code.

```
Exception:
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Firebase.Perf.FirebasePerformance.NewHttpMetric (Java.Net.URL url, System.String httpMethod) [0x00041] in /Users/runner/work/1/s/generated/com.google.firebase.firebase-perf/obj/Release/monoandroid90/generated/src/Firebase.Perf.FirebasePerformance.cs:483 
  at Jacobs.Droid.AndroidHttpClient.StartTracking (System.Net.Http.HttpRequestMessage request, System.String uri, System.String method) [0x00013] in /Users/np65662/Jacobs/WS/Mobile/Performance Monitor/Jacobs.MobileApp/Jacobs.Android/AndroidHttpClient.cs:38 
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at okhttp3.HttpUrl$Companion.parse(Unknown Source:2)
	at okhttp3.HttpUrl.parse(Unknown Source:2)
	at com.google.firebase.perf.util.Utils.stripSensitiveInfo(Utils.java:39)
	at com.google.firebase.perf.metrics.NetworkRequestMetricBuilder.setUrl(NetworkRequestMetricBuilder.java:127)
	at com.google.firebase.perf.metrics.HttpMetric.<init>(HttpMetric.java:60)
	at com.google.firebase.perf.metrics.HttpMetric.<init>(HttpMetric.java:76)
	at com.google.firebase.perf.FirebasePerformance.newHttpMetric(FirebasePerformance.java:444)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/~~VwCH08Kjuwzq7n4pz7oSEQ==/com.jacobs.now.dev-dnVT15Gw6DLWfhsGE-qLhw==/base.apk"],nativeLibraryDirectories=[/data/app/~~VwCH08Kjuwzq7n4pz7oSEQ==/com.jacobs.now.dev-dnVT15Gw6DLWfhsGE-qLhw==/lib/arm64, /data/app/~~VwCH08Kjuwzq7n4pz7oSEQ==/com.jacobs.now.dev-dnVT15Gw6DLWfhsGE-qLhw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 7 more
```

**Comment by moljac** [comment]
Thans for the feedback.

Runtime exception like:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
```

indicates (with high probability) that issue is in optimization (managed trimming, AOT or R8/proguard). The best bet would be to try to add proguard rules for `kotlin.jvm`

Please open new issue if issue persists
