### ISSUE TITLE
ConvertResourcesCases task faild googsvcsjson

### ISSUE THREAD

**Issue by JoacimWall** [xamarin/GooglePlayServicesComponents#95]
Get this error after update of nugets googleplayservice

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ConvertResourcesCases" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\GitRepos\ActionXamarin\ActionXamarin\ActionAndroid\obj\Release\googsvcsjson'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, SearchOption searchOption)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(ITaskItem item, Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ActionAndroid

**Comment by xanderhurley** [comment]
I am also having this issue, if I do a clean then build, I always get this issue, if i build the 2nd time it builds successfully... 

Not much good when I have a build pipeline that is always failing as its building clean every time. Any idea how I can fix this?
